// SPDX-License-Identifier: MIT
pragma solidity ^0.8.34;

/**
 * @title ZKEmailVerifier Interface
 * @notice Interface for the ZKEmailVerifier contract that verifies a proof generated by the ZKEmailVerifier circuit
 */
interface IZKEmailVerifier {
    /**
     * @notice Thrown when the DKIM registry address is zero or otherwise invalid
     */
    error InvalidDKIMRegistry();
    /**
     * @notice Thrown when the proof verifier address is zero or otherwise invalid
     */
    error InvalidProofVerifier();
    /**
     * @notice Thrown when the public inputs array length does not match the circuit's expected length
     */
    error InvalidPublicInputsLength(uint256 expected, uint256 actual);
    /**
     * @notice Thrown when the DKIM registry reports the provided public key hash as invalid
     */
    error InvalidPublicKey();
    /**
     * @notice Thrown when the proof verifier reports the proof as invalid
     */
    error InvalidProof();

    /**
     * @notice Verifies a proof
     * @param proof The proof to verify
     * @param publicInputs The public inputs to the proof
     * @dev Reverts with one of the interface-defined errors on failure
     */
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view;
}
