[package]
name = "sdk_noir"
type = "bin"
authors = ["Aditya Bisht <adityabisht64@gmail.com>"]
compiler_version = ">=1.0.0"

[dependencies]
zkemail = { tag = "v0.4.3", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
zkregex = { tag = "2.1.2", git = "https://github.com/zkemail/zk-regex", directory = "noir" }