// SPDX-License-Identifier: MIT
pragma solidity ^0.8.34;

/**
 * @title ZKEmailVerifier Interface
 * @notice Interface for the ZKEmailVerifier contract that verifies a proof generated by the ZKEmailVerifier circuit
 */
interface IZKEmailVerifier {
    /**
     * @notice Verifies a proof
     * @param proof The proof to verify
     * @param publicInputs The public inputs to the proof
     * @dev Reverts if the DKIM public key hash check fails or the Groth16 proof is invalid
     */
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view;
}
