name: Build and Push Circom Image

on:
  push:
    branches:
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  trigger-cloud-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Get the short SHA for tagging
      - name: Get Short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Authenticate with Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Create a Cloud Build config file
      - name: Create Cloud Build Config
        run: |
          cat > cloudbuild.yaml << EOF
          steps:
          - name: 'gcr.io/cloud-builders/docker'
            args: [
              'build',
              '-f', 'circom/Dockerfile',
              '-t', 'us-east1-docker.pkg.dev/zkairdrop/circom-sdk-image/circom:latest',
              '-t', 'us-east1-docker.pkg.dev/zkairdrop/circom-sdk-image/circom:${{ steps.sha.outputs.sha }}',
              '.'
            ]
            timeout: '3600s'  # Increase timeout to 1 hour
          images:
          - 'us-east1-docker.pkg.dev/zkairdrop/circom-sdk-image/circom:latest'
          - 'us-east1-docker.pkg.dev/zkairdrop/circom-sdk-image/circom:${{ steps.sha.outputs.sha }}'
          options:
            machineType: 'N1_HIGHCPU_64'  # Use a high-CPU machine for faster builds
            diskSizeGb: '100'
          timeout: '3600s'  # Overall build timeout
          EOF

      # Submit the build to Cloud Build
      - name: Trigger Cloud Build
        run: |
          gcloud builds submit --config=cloudbuild.yaml --project ${{ secrets.GCP_PROJECT_ID }}
