name: Build and Push Circom Image

on:
  push:
    branches:
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Get the short SHA for tagging
      - name: Get Short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Authenticate with Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      # Configure Docker to use Google Artifact Registry
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -f circom/Dockerfile \
            -t us-east1-docker.pkg.dev/zkairdrop/circom-sdk-image/circom:latest \
            -t us-east1-docker.pkg.dev/zkairdrop/circom-sdk-image/circom:${{ steps.sha.outputs.sha }} .

      # Push Docker image
      - name: Push Docker Image
        run: |
          docker push us-east1-docker.pkg.dev/zkairdrop/circom-sdk-image/circom:latest
          docker push us-east1-docker.pkg.dev/zkairdrop/circom-sdk-image/circom:${{ steps.sha.outputs.sha }}
