name: Circom contracts tests

on:
  push:
    paths:
      - 'circom/contracts/**'

jobs:
  run_contracts_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Yarn dependencies
        working-directory: ./circom/contracts
        run: yarn install --frozen-lockfile

      - name: Run forge tests
        working-directory: ./circom/contracts
        run: forge test -vvv
